### PR TITLE
Fix to collapse navbar on page reloads

### PR DESCRIPTION
**Pull request by jamlamberti**
If a user reloads the page, the navbar does not collapse or shrink until the user scrolls. This PR will auto-collapse the navbar if the user is currently more than 50 pixels down from the top of the page.

### CODE REVIEW

**Comment by FireEmerald** [comment]
I scrolled down for about 500px, reloaded using F5 and the navbar shrinked only sometimes in:
- Chrome 46.0.2490.80 m (64-bit)
- Internet Explorer 11.0.9600.18059
- Opera beta 33.0.1990.35

In which browser did you @jamlamberti  tested it?

**Comment by jamlamberti** [comment]
@FireEmerald I am running firefox 41 and Chromium 44.0.2403.89 on Ubuntu 14.04 (64-bit). For me, the navbar only shrinks when I scroll.

**Comment by FireEmerald** [comment]
Ok, found the problem. First of all your patch is over sized and placed at the wrong place in the code.
Sometimes when you reload the site the function `scrollPage()` isn't triggered.

The animated header is handled in [cbpAnimatedHeader.js#L27](https://github.com/IronSummitMedia/startbootstrap-agency/blob/gh-pages/js/cbpAnimatedHeader.js#L27)
The `function init()` is triggered on each reload of the document, so we add here one line:

``` js
scrollPage();
```

[PATCH]
- [x] Fix to collapse navbar on page reloads.
- [x] Reduced height when the navbar gets shrinked. [Example](https://picasaweb.google.com/lh/photo/ZnNQbfQK6qypRM-vtn9Zj1bdpHOGiP-uoTpj1M_isiU)

``` patch
From: FireEmerald <fire.github@gmail.com>
Date: Sat, 31 Oct 2015 13:14:19 +0100
Subject: [PATCH] - Fix to collapse navbar on page reloads.
 - Reduced height when the navbar gets shrinked.
---
 js/cbpAnimatedHeader.js     | 3 ++-
 js/cbpAnimatedHeader.min.js | 2 +-
 2 files changed, 3 insertions(+), 2 deletions(-)

diff --git a/js/cbpAnimatedHeader.js b/js/cbpAnimatedHeader.js
index 4554e2e..6de3e3d 100644
--- a/js/cbpAnimatedHeader.js
+++ b/js/cbpAnimatedHeader.js
@@ -13,9 +13,10 @@ var cbpAnimatedHeader = (function() {
    var docElem = document.documentElement,
        header = document.querySelector( '.navbar-default' ),
        didScroll = false,
-       changeHeaderOn = 300;
+       changeHeaderOn = 220;

    function init() {
+       scrollPage();
        window.addEventListener( 'scroll', function( event ) {
            if( !didScroll ) {
                didScroll = true;
diff --git a/js/cbpAnimatedHeader.min.js b/js/cbpAnimatedHeader.min.js
index 18d66a3..9fd3d80 100644
--- a/js/cbpAnimatedHeader.min.js
+++ b/js/cbpAnimatedHeader.min.js
@@ -8,4 +8,4 @@
  * Copyright 2013, Codrops
  * http://www.codrops.com
  */
-var cbpAnimatedHeader=(function(){var b=document.documentElement,g=document.querySelector(".navbar-default"),e=false,a=300;function f(){window.addEventListener("scroll",function(h){if(!e){e=true;setTimeout(d,250)}},false)}function d(){var h=c();if(h>=a){classie.add(g,"navbar-shrink")}else{classie.remove(g,"navbar-shrink")}e=false}function c(){return window.pageYOffset||b.scrollTop}f()})();
+var cbpAnimatedHeader=(function(){var b=document.documentElement,g=document.querySelector(".navbar-default"),e=false,a=220;function f(){d();window.addEventListener("scroll",function(h){if(!e){e=true;setTimeout(d,250)}},false)}function d(){var h=c();if(h>=a){classie.add(g,"navbar-shrink")}else{classie.remove(g,"navbar-shrink")}e=false}function c(){return window.pageYOffset||b.scrollTop}f()})();
-- 
1.9.5.msysgit.0
```

**Comment by jamlamberti** [comment]
@FireEmerald Ah yes that is a much nicer way of doing it. Thanks! I didn't think about fixing the animated header. Do you want to push the fix to https://github.com/codrops/AnimatedHeader?

**Comment by FireEmerald** [comment]
@jamlamberti https://github.com/codrops/AnimatedHeader/pull/8
You should also create a new pull request here with the shown changes above. This pr should be closed.

**Pull request closed without merging**
