### PR TITLE
fixed Issue #48: Closing modals with esc-key doesn't work

### PR DESCRIPTION
**Pull request by cleptric**
I hope I did everything right regarding the build process

### CODE REVIEW

**Comment by davidtmiller** [comment]
Merged. I tested it out and it's kind of working, but I have to click the modal first. Is there a way to fix this up so the modal doesn't need to be clicked on for the esc key to work? Thank you for your contribution!

**Comment by cleptric** [comment]
@davidtmiller I tested it with safari, chrome and firefox on OSX and couldn't reproduce it. Which Browser do you use?

**Comment by davidtmiller** [comment]
Weird, I was using Chrome on Mac. Interesting...

**Comment by cirino** [comment]
To close with ESC, you have to click the item before. Chrome, Windows 8 and 10.

**Pull request merged**
